#!/bin/bash
# Riddler Digest Research Script - Option C Compatible
# Processes Cheetah's daily summary and generates structured digests

WORKSPACE="/Users/chimpman/.openclaw/workspace-riddler"
CHEETAH_DIR="/Users/chimpman/.openclaw/workspace-cheetah"
REPORTS_DIR="$WORKSPACE/reports"
MEMORY_DIR="$WORKSPACE/memory"

# Today's date
DATE_STR=$(date +%Y-%m-%d)
DAY_OF_WEEK=$(date +%u)  # 1=Mon, 7=Sun

# Topic mapping (matches Cheetah's schedule: ai-dm, vtt, devtools, ai-llm)
case $DAY_OF_WEEK in
    1|5) TOPIC="ai-llm" ;;      # Monday/Friday
    2) TOPIC="devtools" ;;      # Tuesday
    3) TOPIC="vtt" ;;           # Wednesday
    4) TOPIC="ai-dm" ;;         # Thursday
    6|7) TOPIC="mixed" ;;       # Weekend
esac

echo "=========================================="
echo "🧩 Riddler Digest Processor (Option C)"
echo "Date: $DATE_STR"
echo "Topic: $TOPIC"
echo "=========================================="

# Option C paths
DAILY_SUMMARY="$CHEETAH_DIR/reports/daily_summaries/${TOPIC}_${DATE_STR}.md"
LIVING_REPORT="$CHEETAH_DIR/reports/${TOPIC}_Living_Report.md"
KNOWLEDGE_BASE="$CHEETAH_DIR/knowledge/${TOPIC}.json"

SOURCE_FILE=""
SOURCE_TYPE=""

# Priority: Daily Summary > Living Report > Knowledge Base JSON
if [ -f "$DAILY_SUMMARY" ]; then
    SOURCE_FILE="$DAILY_SUMMARY"
    SOURCE_TYPE="daily_summary"
    echo "✅ Found Daily Summary: $DAILY_SUMMARY"
elif [ -f "$LIVING_REPORT" ]; then
    SOURCE_FILE="$LIVING_REPORT"
    SOURCE_TYPE="living_report"
    echo "✅ Found Living Report: $LIVING_REPORT"
elif [ -f "$KNOWLEDGE_BASE" ]; then
    SOURCE_FILE="$KNOWLEDGE_BASE"
    SOURCE_TYPE="knowledge_base"
    echo "✅ Found Knowledge Base: $KNOWLEDGE_BASE"
else
    echo "❌ No source found for $TOPIC on $DATE_STR"
    echo "   Searched:"
    echo "   - $DAILY_SUMMARY"
    echo "   - $LIVING_REPORT"
    echo "   - $KNOWLEDGE_BASE"
    exit 1
fi

# Create digest output directory
DIGEST_DIR="$REPORTS_DIR/digests"
mkdir -p "$DIGEST_DIR"

DIGEST_PATH="$DIGEST_DIR/${TOPIC}_${DATE_STR}_digest.md"

echo ""
echo "Processing $SOURCE_TYPE..."
echo ""

# Generate digest header
cat > "$DIGEST_PATH" << EOF
# Riddler's Digest: ${TOPIC} Research - ${DATE_STR}

*Source: ${SOURCE_TYPE}*  
*Generated: $(date -Iseconds)*

---

## 📋 Digest Overview

This digest analyzes ${TOPIC} research findings and identifies:
- Key patterns and trends
- Notable projects worth tracking
- Strategic insights for developers and users
- Actionable recommendations

---

## 🔍 Key Findings

EOF

# Add source content analysis (placeholder for LLM processing)
echo "### Source: ${SOURCE_FILE}" >> "$DIGEST_PATH"
echo "" >> "$DIGEST_PATH"
echo "\`\`\`" >> "$DIGEST_PATH"

if [ "$SOURCE_TYPE" = "knowledge_base" ]; then
    # Parse JSON for key stats
    cat "$SOURCE_FILE" | jq -r '[
        "Total projects tracked: \(.totalFindings // 0)",
        "Last updated: \(.lastUpdated // "unknown")",
        "Top projects by stars:",
        (.projects | to_entries | sort_by(.value.stars) | reverse[:5] | map("- \(.value.displayName): \(.value.stars)⭐") | join("\n"))
    ] | join("\n")' >> "$DIGEST_PATH" 2>/dev/null || echo "Error parsing JSON" >> "$DIGEST_PATH"
else
    # Include summary from markdown
    head -100 "$SOURCE_FILE" >> "$DIGEST_PATH"
fi

echo "\`\`\`" >> "$DIGEST_PATH"
echo "" >> "$DIGEST_PATH"

# Add analysis section (for LLM to fill in)
cat >> "$DIGEST_PATH" << EOF

---

## 📊 Pattern Analysis

*[To be completed by Riddler via LLM analysis]*

### Trends Identified
- 
- 
- 

### Emerging Technologies
- 
- 

### Competitive Landscape
- 

---

## 🎯 Recommendations

### For Developers
1. 
2. 

### For Users
1. 
2. 

### Watch List
- 
- 

---

## 📁 Source Reference

- **Type:** ${SOURCE_TYPE}
- **Path:** ${SOURCE_FILE}
- **Date Range:** $(date +%Y-%m-%d)

---

*This digest was generated by Riddler as part of the Cheetah→Riddler cascade workflow.*
EOF

# Create metadata JSON
META_PATH="$DIGEST_DIR/${TOPIC}_${DATE_STR}_meta.json"
cat > "$META_PATH" << EOF
{
  "date": "$DATE_STR",
  "topic": "$TOPIC",
  "source_type": "$SOURCE_TYPE",
  "source_path": "$SOURCE_FILE",
  "digest_path": "$DIGEST_PATH",
  "processed": true,
  "timestamp": "$(date -Iseconds)"
}
EOF

echo "=========================================="
echo "✅ DIGEST COMPLETE"
echo "=========================================="
echo ""
echo "Output:"
echo "  Digest: $DIGEST_PATH"
echo "  Metadata: $META_PATH"
echo "  Words: $(wc -w < "$DIGEST_PATH")"
echo ""

# Display first few lines
head -30 "$DIGEST_PATH"

exit 0
